trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

  
steps:

- task: CopyFiles@2

  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'

  inputs:

    SourceFolder: web

    TargetFolder: '$(Build.ArtifactStagingDirectory)'



- task: PublishBuildArtifacts@1

  displayName: 'Publish Artifact: drop'



- task: Docker@1

  displayName: 'Build an image'

  inputs:

    containerregistrytype: 'Container Registry'

    includeSourceTags: true

    includeLatestTag: true



- task: AmazonWebServices.aws-vsts-tools.ECRPushImage.ECRPushImage@1

  displayName: 'Push Image: Docker to ECR'

  inputs:

    awsCredentials: 'AWS_ECR_conn'

    regionName: 'us-east-1'

    sourceImageName: '$(Build.Repository.Name)'

    repositoryName: 'ahossam-onica'



